services:
  app:
    image: ghcr.io/danischuetz/maniok/maniok-webapp:latest
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: https://app.maniok.io
    expose:
      - "3000"
      
  app_staging:
    image: ghcr.io/danischuetz/maniok/maniok-webapp:staging
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: https://staging.maniok.io
    expose:
      - "3000"

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: