services:
  maniok_production:
    image: ghcr.io/danischuetz/maniok/maniok-webapp:latest
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: https://app.maniok.io
    expose:
      - "3000"
    networks:
      - web
      
  maniok_staging:
    image: ghcr.io/danischuetz/maniok/maniok-webapp:staging
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: https://staging.maniok.io
    expose:
      - "3000"
    networks:
      - web

networks:
  web:
    external: true