name: Build & Publish Maniok Preview Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run workflow on (required for production)'
        required: false
      environment:
        description: 'Environment to deploy to [staging, production]'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      dockerfile: Dockerfile.Preview
      image_name: maniok-preview
      tag: ${{ github.event.inputs.tag }}
      environment: ${{ github.event.inputs.environment }}
